version: '3'
services:
  app:
    build:
      context: ../../
      dockerfile: build/package/development/Dockerfile
    ports:
      - '8080:8080'
    links:
      - postgres
    volumes:
      - ../../:/go/src/app
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: development
    env_file:
      - ../../build/package/development/secrets.env
    stdin_open: true
    tty: true


  postgres:
    image: postgres:13.2-alpine
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: development
    volumes:
      - postgres-data:/var/lib/postgresql/data


  migrate:
    image: migrate/migrate:4
    links:
      - postgres
    volumes:
      - ../../db/migrations:/migrations


volumes:
  postgres-data: {}
